name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'

      - name: Install dependencies
        run: |
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          echo "$TIMESTAMP [INFO] - Installing dependencies..."
          if flutter pub get; then
            echo "$TIMESTAMP [INFO] - Dependencies installed successfully."
          else
            echo "$TIMESTAMP [ERROR] - Dependency installation failed!"
            exit 1
          fi

      - name: Clean project
        run: |
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          echo "$TIMESTAMP [INFO] - Cleaning project..."
          if flutter clean; then
            echo "$TIMESTAMP [INFO] - Clean successful."
          else
            echo "$TIMESTAMP [WARNING] - Clean operation failed, continuing..."
          fi

      - name: Build APK
        id: build_apk
        run: |
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          echo "$TIMESTAMP [INFO] - Starting APK build process..."
          
          MAX_RETRIES=3
          RETRY_DELAY=2
          
          for i in $(seq 1 $MAX_RETRIES); do
            TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
            echo "$TIMESTAMP [INFO] - Build attempt $i..."
            
            if flutter build apk --split-per-abi --verbose; then
              echo "$TIMESTAMP [INFO] - Build completed successfully."
              exit 0
            else
              echo "$TIMESTAMP [WARNING] - Build failed on attempt $i."
              if [ $i -lt $MAX_RETRIES ]; then
                echo "$TIMESTAMP [INFO] - Retrying in $((RETRY_DELAY ** i)) seconds..."
                sleep $((RETRY_DELAY ** i))
              else
                echo "$TIMESTAMP [ERROR] - Build failed after $MAX_RETRIES attempts!"
                exit 1
              fi
            fi
          done

      - name: Check build directory
        if: success()
        run: |
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          echo "$TIMESTAMP [INFO] - Checking build output directories..."
          
          APK_FILES=$(find build/app/outputs -type f \( -name "*.apk" -o -name "*.aab" \) 2>/dev/null)
          
          if [ -n "$APK_FILES" ]; then
            echo "$TIMESTAMP [INFO] - APK/AAB files found:"
            echo "$APK_FILES"
          else
            echo "$TIMESTAMP [ERROR] - No APK/AAB files found!"
            exit 1
          fi

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            build/app/outputs/apk/release/*.apk
            build/app/outputs/bundle/release/*.aab
            build/app/outputs/flutter-apk/*.apk

      - name: Print Environment Variables
        if: success()
        run: |
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          echo "$TIMESTAMP [INFO] - Printing environment variables..."
          printenv

      - name: Handle Build Errors and Notify
        if: failure()
        run: |
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          echo "$TIMESTAMP [ERROR] - Build failed during the APK build process! Please check the logs for details."

      - name: Notify on Success
        if: success()
        run: |
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          echo "$TIMESTAMP [INFO] - Build succeeded!"
