name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'

      - name: Install dependencies
        run: flutter pub get

      - name: Clean project
        run: flutter clean

      - name: Build APK
        id: build_apk
        run: |
          echo "Building APK..."
          flutter build apk --split-per-abi --verbose

      - name: Check build directory
        if: success()
        run: |
          echo "Checking build output directories..."
          find build/app/outputs -type f -name "*.apk"

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            build/app/outputs/apk/release/*.apk
            build/app/outputs/bundle/release/*.aab
            build/app/outputs/flutter-apk/*.apk

      - name: Print Environment Variables
        if: success()
        run: |
          echo "Environment Variables:"
          printenv

      - name: Handle Build Errors
        if: failure()
        run: |
          echo "Build failed! Please check the logs for details."

      - name: Notify on Success
        if: success()
        run: |
          echo "Build succeeded!"

      - name: Notify on Failure
        if: failure()
        run: |
          echo "Build failed! Please check the logs for details."
