name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'

      - name: Install dependencies
        run: |
          echo "$(date '+%Y-%m-%d %H:%M:%S') [INFO] - Installing dependencies..."
          flutter pub get

      - name: Clean project
        run: |
          echo "$(date '+%Y-%m-%d %H:%M:%S') [INFO] - Cleaning project..."
          flutter clean

      - name: Build APK
        id: build_apk
        run: |
          echo "$(date '+%Y-%m-%d %H:%M:%S') [INFO] - Building APK..."
          for i in {1..3}; do 
            flutter build apk --split-per-abi --verbose && break || \
            echo "$(date '+%Y-%m-%d %H:%M:%S') [WARNING] - Build failed, retrying..."; 
            sleep $((2 ** i)); 
          done

      - name: Check build directory
        if: success()
        run: |
          echo "$(date '+%Y-%m-%d %H:%M:%S') [INFO] - Checking build output directories..."
          find build/app/outputs -type f -name "*.apk"

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            build/app/outputs/apk/release/*.apk
            build/app/outputs/bundle/release/*.aab
            build/app/outputs/flutter-apk/*.apk

      - name: Print Environment Variables
        if: success()
        run: |
          echo "$(date '+%Y-%m-%d %H:%M:%S') [INFO] - Environment Variables:"
          printenv

      - name: Handle Build Errors and Notify
        if: failure()
        run: |
          echo "$(date '+%Y-%m-%d %H:%M:%S') [ERROR] - Build failed during the APK build process! Please check the logs for details."
          echo "$(date '+%Y-%m-%d %H:%M:%S') [ERROR] - Build failed!"
          echo "$(date '+%Y-%m-%d %H:%M:%S') [INFO] - Build failed!"

      - name: Notify on Success
        if: success()
        run: |
          echo "$(date '+%Y-%m-%d %H:%M:%S') [INFO] - Build succeeded!"
