name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'

      - name: Install dependencies
        run: |
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          echo "$TIMESTAMP [INFO] - Installing dependencies..."
          flutter pub get

      - name: Clean project
        run: |
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          echo "$TIMESTAMP [INFO] - Cleaning project..."
          flutter clean

      - name: Build APK
        id: build_apk
        run: |
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          echo "$TIMESTAMP [INFO] - Building APK..."
          
          for i in {1..3}; do 
            if flutter build apk --split-per-abi --verbose; then
              echo "$TIMESTAMP [INFO] - Build completed successfully."
              exit 0
            else
              echo "$TIMESTAMP [WARNING] - Build failed, retrying in $((2 ** i)) seconds..."
              sleep $((2 ** i))
            fi
          done
          
          echo "$TIMESTAMP [ERROR] - Build failed after multiple attempts!"
          exit 1

      - name: Check build directory
        if: success()
        run: |
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          echo "$TIMESTAMP [INFO] - Checking build output directories..."
          find build/app/outputs -type f -name "*.apk"

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            build/app/outputs/apk/release/*.apk
            build/app/outputs/bundle/release/*.aab
            build/app/outputs/flutter-apk/*.apk

      - name: Print Environment Variables
        if: success()
        run: |
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          echo "$TIMESTAMP [INFO] - Environment Variables:"
          printenv

      - name: Handle Build Errors and Notify
        if: failure()
        run: |
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          echo "$TIMESTAMP [ERROR] - Build failed during the APK build process! Please check the logs for details."

      - name: Notify on Success
        if: success()
        run: |
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          echo "$TIMESTAMP [INFO] - Build succeeded!"
